Repository Cryptonomic/Conseil, pull requests merged in 2018-12, with the labels that each got.

#200 Conseil 194: account diffs
  .gitignore
  build.sbt
  doc/conseil.sql
  src/main/resources/application.conf
  src/main/resources/logback.xml
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/db/DatabaseQueryExecution.scala
  src/main/scala/tech/cryptonomic/conseil/scripts/GenSchema.scala
  src/main/scala/tech/cryptonomic/conseil/scripts/NodeStreamingBenchmarks.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/ApiFiltering.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/ApiOperations.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/Tables.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperations.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosErrors.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosNodeInterface.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosNodeOperator.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosTypes.scala
  src/main/scala/tech/cryptonomic/conseil/util/JsonUtil.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/InMemoryDatabase.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/PlatformDiscoveryOperationsTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTest.scala
  src/test/scala/tech/cryptonomic/conseil/util/JsonUtilTest.scala
Labels: bug

#172 README updates for DevOps
  README.md
  src/main/resources/application.conf
Labels: documentation

#173 Conseil-103: continued work on avoiding partial functions
  .gitignore
  build.sbt
  src/main/resources/application.conf
  src/main/resources/developer.conf
  src/main/scala/tech/cryptonomic/conseil/Conseil.scala
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/config/ConseilAppConfig.scala
  src/main/scala/tech/cryptonomic/conseil/config/LorreAppConfig.scala
  src/main/scala/tech/cryptonomic/conseil/config/Platforms.scala
  src/main/scala/tech/cryptonomic/conseil/config/Security.scala
  src/main/scala/tech/cryptonomic/conseil/config/Shared.scala
  src/main/scala/tech/cryptonomic/conseil/config/package.scala
  src/main/scala/tech/cryptonomic/conseil/db/DatabaseQueryExecution.scala
  src/main/scala/tech/cryptonomic/conseil/routes/PlatformDiscovery.scala
  src/main/scala/tech/cryptonomic/conseil/scripts/GenSchema.scala
  src/main/scala/tech/cryptonomic/conseil/scripts/NodeStreamingBenchmarks.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/FeeOperations.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/PlatformDiscoveryOperations.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperations.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosNodeInterface.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosNodeOperator.scala
  src/main/scala/tech/cryptonomic/conseil/util/ConfigUtil.scala
  src/main/scala/tech/cryptonomic/conseil/util/JsonUtil.scala
  src/main/scala/tech/cryptonomic/conseil/util/SecurityUtil.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/PlatformDiscoveryOperationsTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTest.scala
  src/test/scala/tech/cryptonomic/conseil/util/ConfigUtilTest.scala
  src/test/scala/tech/cryptonomic/conseil/util/JsonUtilTest.scala
Labels: refactor/tech-debt
