Repository Cryptonomic/Conseil, pull requests merged in 2019-04, with the labels that each got.

#308 Bug fixes and backwards compatibility measures for v1 API
  src/main/scala/tech/cryptonomic/conseil/routes/DataHelpers.scala
  src/main/scala/tech/cryptonomic/conseil/routes/openapi/ApiFilterFromQueryString.scala
  src/main/scala/tech/cryptonomic/conseil/routes/openapi/DataJsonSchemas.scala
  src/main/scala/tech/cryptonomic/conseil/routes/openapi/TezosEndpoints.scala
Labels: bug, enhancement

#313 Filtering null values when fetching attribute values
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperations.scala
Labels: bug

#319 Fix logback layout using latest format
  src/main/resources/logback.xml
Labels: refactor/tech-debt

#320 Conseil 301: Interleave the account processing with block batches
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
Labels: refactor/tech-debt

#326 Conseil 325: Include time to process accounts of each page block in the timeout
  src/main/resources/reference.conf
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/config/Shared.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosNodeOperatorTest.scala
Labels: bug

#340 Conseil recursive sqlbuilder
  src/main/scala/tech/cryptonomic/conseil/util/DatabaseUtil.scala
  src/test/scala/tech/cryptonomic/conseil/util/DatabaseUtilTest.scala
Labels: refactor/tech-debt
