Repository Cryptonomic/Conseil, pull requests merged in 2019-12, with the labels that each got.

#639 638 - Add missing metadata cycle information on accounts checkpoint data
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/Tables.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperations.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTest.scala
Labels: bug

#640 637 - The predicate groups were not being considered to build the query
  src/main/scala/tech/cryptonomic/conseil/generic/chain/DataTypes.scala
  src/main/scala/tech/cryptonomic/conseil/util/DatabaseUtil.scala
  src/test/scala/tech/cryptonomic/conseil/util/DatabaseUtilTest.scala
Labels: bug

#642 Update out-of-date documentation
  README.md
  docs/publishing.md
Labels: documentation

#641 637 - Add a regression test to verify groupings of query predicates
  CONTRIBUTION.md
  src/it/resources/groupingPredicatesQuery.body.json
  src/it/resources/groupingPredicatesQuery.response.json
  src/it/scala/tech/cryptonomic/conseil/client/EndpointClient.scala
  src/it/scala/tech/cryptonomic/conseil/client/RegressionRun.scala
Labels: tests

#617 Conseil 600/603 add cycle and governance period to bakers and rights tables
  sql/conseil.sql
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/DatabaseConversions.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/Tables.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperations.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosNodeFetchers.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosNodeOperator.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTest.scala
Labels: data enhancement

#651 650 - Fix the counting of levels to load when the chain is started
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosNodeOperator.scala
Labels: bug
