Repository Cryptonomic/Conseil, pull requests merged in 2019-10, with the labels that each got.

#575 Add the ability to configure an API key when launching in docker.
  README.md
  docker/entrypoint.sh
  docker/template.conf
Labels: enhancement

#582 Various bug fixes for proto5 logic
  doc/conseil.sql
  src/main/resources/metadata.conf
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/DatabaseConversions.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/JsonDecoders.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/Tables.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperations.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosNodeFetchers.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosNodeOperator.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosTypes.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/michelson/renderer/MichelsonRenderer.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/InMemoryDatabase.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/JsonDecodersTestFixtures.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTestFixtures.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosPlatformDiscoveryOperationsTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosTypesTest.scala
Labels: bug

#583 Metadata updates + minor fixes for proto5 code
  src/main/resources/metadata/tezos.alphanet.conf
  src/main/resources/metadata/tezos.mainnet.conf
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/DatabaseConversions.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/michelson/renderer/MichelsonRenderer.scala
Labels: bug

#611 Add documentation for additional db configuration, using ssl
  docs/extra-custom-config.md
Labels: documentation

#609 Remove hard coding from conseil.sql
  README.md
  sql/conseil.sql
Labels: bug
