Repository Cryptonomic/Conseil, pull requests merged in 2020-07, with the labels that each got.

#869 868 - output txid in bitcoin.inputs table
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/discovery/GenericPlatformDiscoveryOperationsTest.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/bitcoin/Tables.scala
  sql/conseil.sql
Labels: Btc-Int

#854 868-1 - JSON-RPC client
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/rpc/RpcClient.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/rpc/RpcClientTest.scala
  project/Dependencies.scala
Labels: Btc-Int

#865 868-2 - Bitcoin JSON-RPC client
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/bitcoin/rpc/BitcoinRpcClient.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/bitcoin/rpc/BitcoinRpcCommands.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/bitcoin/rpc/json/Block.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/bitcoin/rpc/json/BlockchainInfo.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/bitcoin/rpc/json/Transaction.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/bitcoin/BitcoinFixtures.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/bitcoin/rpc/BitcoinRpcClientTest.scala
Labels: Btc-Int

#874 873 - automation of separate slick models per chain
  conceil.yaml
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/Tables.scala
  conseil-schema/src/main/resources/application.conf
  conseil-schema/src/main/scala/tech/cryptonomic/conseil/schema/GenSchema.scala
  project/Dependencies.scala
Labels: Btc-Int, bug

#866 868-3 - Bitcoin persistence
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/bitcoin/BitcoinPersistence.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/bitcoin/BitcoinInMemoryDatabaseSetup.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/bitcoin/BitcoinPersistenceTest.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/bitcoin/BitcoinStubs.scala
  project/Dependencies.scala
Labels: Btc-Int

#877 868 - Missing Bitcoin DB fixtures
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/bitcoin/BitcoinFixtures.scala
Labels: Btc-Int

#858 Bitcoin data endpoint
  conseil-api/src/main/resources/metadata.conf
  conseil-api/src/main/resources/metadata/bitcoin.mainnet.conf
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/ConseilApi.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/config/ConseilAppConfig.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/openapi/OpenApiDoc.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/Api.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/TezosApi.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/ApiDataEndpoints.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/ApiDataHelpers.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/ApiDataJsonSchemas.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/ApiDataTypes.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/ApiFilter.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/bitcoin/BitcoinDataEndpoints.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/bitcoin/BitcoinDataHelpers.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/bitcoin/BitcoinDataOperations.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/bitcoin/BitcoinDataQueries.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/bitcoin/BitcoinDataRoutes.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/bitcoin/BitcoinFilter.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/bitcoin/BitcoinFilterFromQueryString.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataEndpoints.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataHelpers.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataJsonSchemas.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataOperations.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataRoutes.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosFilter.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosFilterFromQueryString.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/ApiDataHelpersTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/ApiDataTypesTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/bitcoin/BitcoinDataQueriesTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/bitcoin/BitcoinDataRoutesTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataHelpersTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataOperationsTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataRoutesTest.scala
  conseil-common/src/main/resources/reference.conf
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/bitcoin/BitcoinPersistence.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/bitcoin/BitcoinTypes.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/config/Platforms.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/TezosTypes.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/tezos/TezosOpticsTest.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/tezos/TezosTypesTest.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/config/LorreAppConfig.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/config/LorreConfiguration.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/logging/LorreInfoLogging.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseConversions.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosIndexer.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosJsonDecoders.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeFetchers.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeOperator.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/bigmaps/BigMapsConversions.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/processing/AccountsProcessor.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/processing/AccountsResetHandler.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/JsonDecodersTestFixtures.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseConversionsTest.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperationsTest.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperationsTestFixtures.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosJsonDecodersTest.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeOperatorTest.scala
Labels: Btc-Int

#879 Change the mechanism of reading configuration as well as the style of it
  Dockerfile
  conseil-api/src/main/resources/application.conf
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/ConseilApi.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/ConseilMainOutput.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/config/ConseilAppConfig.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/metadata/MetadataService.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/config/ConseilAppConfigTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/metadata/MetadataServiceTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/ApiDataTypesTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/bitcoin/BitcoinDataRoutesTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataRoutesTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/discovery/GenericPlatformDiscoveryOperationsTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/discovery/PlatformDiscoveryTest.scala
  conseil-common/src/main/resources/reference.conf
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/config/PlatformConfigurationHint.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/config/Platforms.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/config/package.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/io/MainOutputs.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/config/PlatformsTest.scala
  conseil-lorre/src/main/resources/application.conf
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/Lorre.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/config/LorreAppConfig.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeInterface.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/config/LorreAppConfigTest.scala
  docker/docker-compose.yml
  docker/entrypoint.sh
  docker/template.conf
  project/Dependencies.scala
Labels: Btc-Int

#867 868-4 - Lorre for Bitcoin
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/metadata/MetadataServiceTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/bitcoin/BitcoinDataRoutesTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataOperationsTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/discovery/GenericPlatformDiscoveryOperationsTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/discovery/PlatformDiscoveryTest.scala
  conseil-common/src/main/resources/reference.conf
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/bitcoin/BitcoinPersistence.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/config/Platforms.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/io/MainOutputs.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/bitcoin/BitcoinPersistenceTest.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/config/PlatformsTest.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/Lorre.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/bitcoin/BitcoinIndexer.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/bitcoin/BitcoinOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/config/LorreAppConfig.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/bitcoin/BitcoinOperationsTest.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperationsTest.scala
  docker-compose.yml
Labels: Btc-Int

#876 868-5 - Bitcoin accounts
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/bitcoin/Views.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/bitcoin/BitcoinDbViewsTest.scala
  sql/conseil.sql
Labels: Btc-Int

#882 881 - make consistent use of block level definition
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataOperations.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataHelpersTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataOperationsTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/discovery/GenericPlatformDiscoveryOperationsTest.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/config/Shared.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/Tables.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/TezosTypes.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/tezos/TezosOpticsTest.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/logging/LorreProgressLogging.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseConversions.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosIndexedDataOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeFetchers.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeOperator.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/bigmaps/BigMapsOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/processing/AccountsProcessor.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/processing/AccountsResetHandler.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/processing/BakersProcessor.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/processing/BakingAndEndorsingRightsProcessor.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/sql/DefaultDatabaseOperationsTest.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseConversionsTest.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperationsTest.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperationsTestFixtures.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeOperatorTest.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/bigmaps/BigMapsOperationsTest.scala
  project/Dependencies.scala
  sql/conseil.sql
Labels: data enhancement, dataschema-change-required, refactor/tech-debt

#888 887 - db schema for Ethereum blocks, transactions and logs
  build.sbt
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/ethereum/Tables.scala
  sql/conseil.sql
Labels: Eth-Int

#885 187-1 fork detection
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/ForkDetector.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/forking/ForkDetectorSpec.scala
Labels: enhancement

#891 887-1 - Ethereum JSON-RPC client and persistence
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/ethereum/EthereumPersistence.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/ethereum/rpc/EthereumRpcClient.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/ethereum/rpc/EthereumRpcCommands.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/ethereum/rpc/json/Block.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/ethereum/rpc/json/Log.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/ethereum/rpc/json/Transaction.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/ethereum/EthereumFixtures.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/ethereum/EthereumInMemoryDatabaseSetup.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/ethereum/EthereumPersistenceTest.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/ethereum/EthereumStubs.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/ethereum/rpc/EthereumRpcClientTest.scala
Labels: Eth-Int
