Repository Cryptonomic/Conseil, pull requests merged in 2020-05, with the labels that each got.

#777 Use a function to read hex-account addresses for tokens on big map diffs key
  src/main/scala/tech/cryptonomic/conseil/tezos/bigmaps/BigMapsConversions.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/bigmaps/BigMapsOperations.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/michelson/contracts/TokenContracts.scala
  src/main/scala/tech/cryptonomic/conseil/util/CryptoUtil.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/michelson/contracts/TokenContractsTest.scala
  src/test/scala/tech/cryptonomic/conseil/util/CryptoUtilTest.scala
Labels: refactor/tech-debt

#778 Swap handling of micheline parameters to be more obvious
  src/main/scala/tech/cryptonomic/conseil/tezos/DatabaseConversions.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosNodeOperator.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosTypes.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/DatabaseConversionsTest.scala
Labels: bug

#771 Tests: update the broken regression tests
  src/it/resources/groupingPredicatesQuery.body.json
  src/it/resources/groupingPredicatesQuery.response.json
  src/it/scala/tech/cryptonomic/conseil/client/EndpointClient.scala
  src/it/scala/tech/cryptonomic/conseil/client/RegressionFixtures.scala
  src/it/scala/tech/cryptonomic/conseil/client/RegressionRun.scala
Labels: tests

#780 Fix correct handling of parameters conversion in internal operations
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosNodeOperator.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosTypes.scala
Labels: bug

#790 Allow specifying JVM settings with reasonable defaults
  docker/entrypoint.sh
Labels: bug

#792 Fix JVM settings in Docker compose
  docker/entrypoint.sh
Labels: bug

#796 795 - Guarantee safe use of the discardGenesis function
  conseil-common-testkit/src/main/scala/tech/cryptonomic/conseil/common/testkit/InMemoryDatabase.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/DatabaseConversions.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/TezosOptics.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/TezosTypes.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/tezos/DatabaseConversionsTest.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/tezos/TezosDatabaseOperationsTest.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/Lorre.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeOperator.scala
Labels: bug

#804 791 - make the token handling compatible with tzBTC format
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/util/CryptoUtil.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/util/CryptoUtilTest.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/michelson/contracts/TokenContracts.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/michelson/contracts/TokenContractsTest.scala
Labels: data enhancement

#810 807 - Handle multiple big-map updates and copy for single batch
  conseil-api/src/test/resources/logback-test.xml
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/TezosOptics.scala
  conseil-lorre/src/main/resources/logback.xml
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/bigmaps/BigMapsOperations.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperationsTestFixtures.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/bigmaps/BigMapsOperationsTest.scala
Labels: bug

#812 807 - Handle multiple big-map updates and copy for single batch [backport]
  src/main/resources/logback.xml
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosOptics.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/bigmaps/BigMapsOperations.scala
  src/test/resources/logback-test.xml
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTestFixtures.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/bigmaps/BigMapOperationsTest.scala
Labels: bug

#814 813 - Restore Camel Case format for TNS configuration
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/config/LorreAppConfig.scala
Labels: bug

#815 809 - Avoid runtime failure of metadata check for genesis block crashing Lorre
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosIndexer.scala
Labels: bug

#816 809 - Avoid runtime failure of metadata check for genesis block crashing Lorre [backport]
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/DatabaseConversions.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosNodeOperator.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosOptics.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosTypes.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/DatabaseConversionsTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTest.scala
Labels: bug
