Repository Cryptonomic/Conseil, pull requests merged in 2020-03, with the labels that each got.

#708 700 - only store big maps for applied ops
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/DatabaseConversions.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosTypes.scala
Labels: bug

#711 Removed typo in tezos.carthagenet.conf
  src/main/resources/metadata/tezos.carthagenet.conf
  src/main/resources/metadata/tezos.mainnet.conf
Labels: bug

#715 Remove the existing constraint between big maps and content
  sql/conseil.sql
  src/main/scala/tech/cryptonomic/conseil/tezos/Tables.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/JsonDecodersTestFixtures.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosPlatformDiscoveryOperationsTest.scala
Labels: bug

#732 Indexes to make governance table additions more performant
  sql/conseil.sql
Labels: bug

#736 Extract the csv to table row parsing to a dedicated object in config
  src/main/resources/registered_tokens/mainnet.csv
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperations.scala
  src/main/scala/tech/cryptonomic/conseil/util/ConfigUtil.scala
  src/test/resources/registered_tokens/testnet.csv
  src/test/scala/tech/cryptonomic/conseil/util/ConfigUtilTest.scala
Labels: refactor/tech-debt

#743 Bump scala compiler to latest compatible version: 2.12.10
  .travis.yml
  build.sbt
Labels: refactor/tech-debt

#744 CI speed-up with latest sbt and simplified script
  .travis.yml
  README.md
  docs/README.md
  project/build.properties
Labels: refactor/tech-debt

#722 679 - store token balances
  build.sbt
  docker-compose.yml
  sql/conseil.sql
  src/main/resources/registered_tokens/babylonnet.csv
  src/main/resources/registered_tokens/carthagenet.csv
  src/main/resources/registered_tokens/mainnet.csv
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/BigMapsOperations.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/DatabaseConversions.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/Tables.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperations.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/michelson/contracts/TokenContracts.scala
  src/main/scala/tech/cryptonomic/conseil/util/ConfigUtil.scala
  src/main/scala/tech/cryptonomic/conseil/util/CryptoUtil.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/ApiOperationsTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/BigMapOperationsTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTestFixtures.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosPlatformDiscoveryOperationsTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/michelson/contracts/TokenContractsTest.scala
  src/test/scala/tech/cryptonomic/conseil/util/CryptoUtilTest.scala
Labels: data enhancement
