Repository Cryptonomic/Conseil, pull requests merged in 2020-04, with the labels that each got.

#755 Fix platform tests for added indexing of operations columns
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosPlatformDiscoveryOperationsTest.scala
Labels: bug

#753 Bugfix/752 only change token balances when applied
  src/main/scala/tech/cryptonomic/conseil/tezos/DatabaseConversions.scala
Labels: bug

#756 Refactor to extract big-map logic from converters
  src/main/scala/tech/cryptonomic/conseil/tezos/BigMapsOperations.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/DatabaseConversions.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosOptics.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTestFixtures.scala
Labels: refactor/tech-debt

#738 Tuned connection settings according to emperical data
  src/main/resources/reference.conf
Labels: enhancement

#757 Point project README to wiki
  README.md
  docs/.nojekyll
  docs/README.md
  docs/extra-custom-config.md
  docs/index.html
  docs/publishing.md
  sql/Table Schema.ods
  sql/Tezos Operation Schema.ods
  src/main/resources/conseil.key
  src/main/resources/conseil.p12
  src/main/resources/conseil.pem
Labels: enhancement

#767 Rename the token contract type column and use commas as separator
  sql/conseil.sql
  src/main/resources/registered_tokens/babylonnet.csv
  src/main/resources/registered_tokens/carthagenet.csv
  src/main/resources/registered_tokens/mainnet.csv
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/Tables.scala
  src/test/resources/registered_tokens/testnet.csv
Labels: refactor/tech-debt

#759 723 - Add tezos names table to track entries in tezos naming service
  sql/conseil.sql
  src/main/resources/logback.xml
  src/main/resources/reference.conf
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/config/LorreAppConfig.scala
  src/main/scala/tech/cryptonomic/conseil/config/Platforms.scala
  src/main/scala/tech/cryptonomic/conseil/io/MainOutputs.scala
  src/main/scala/tech/cryptonomic/conseil/scripts/NodeStreamingBenchmarks.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/DatabaseConversions.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/Tables.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperations.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosNodeOperator.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosOptics.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/app/TezosNamesOperations.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/bigmaps/BigMapsConversions.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/bigmaps/BigMapsOperations.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/michelson/contracts/TNSContract.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/michelson/contracts/TokenContracts.scala
  src/main/scala/tech/cryptonomic/conseil/util/ConfigUtil.scala
  src/main/scala/tech/cryptonomic/conseil/util/OptionUtil.scala
  src/test/scala/tech/cryptonomic/conseil/metadata/MetadataServiceTest.scala
  src/test/scala/tech/cryptonomic/conseil/routes/PlatformDiscoveryTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/ApiOperationsTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/DataTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/DataTypesTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperationsTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/TezosPlatformDiscoveryOperationsTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/bigmaps/BigMapOperationsTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/michelson/contracts/TNSContractsTest.scala
  src/test/scala/tech/cryptonomic/conseil/tezos/michelson/contracts/TokenContractsTest.scala
  src/test/scala/tech/cryptonomic/conseil/util/ConfigUtilTest.scala
Labels: enhancement
