Repository Cryptonomic/Conseil, pull requests merged in 2020-06, with the labels that each got.

#823 791 - Add the missing token to the registry
  conseil-lorre/src/main/resources/registered_tokens/mainnet.csv
Labels: data enhancement

#846 844 - missing proposals data from governance [backport]
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
Labels: bug

#847 843 - Correct rolls counts computation for governance [backport]
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/DatabaseConversions.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperations.scala
Labels: bug

#848 843 - Correct rolls counts for governance [release merge] take 2
  src/main/scala/tech/cryptonomic/conseil/Lorre.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/DatabaseConversions.scala
  src/main/scala/tech/cryptonomic/conseil/tezos/TezosDatabaseOperations.scala
Labels: bug

#839 838 - refactor: simplify governance-related code
  build.sbt
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/metadata/MetadataServiceTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/discovery/PlatformDiscoveryTest.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/bitcoin/Tables.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/TezosOptics.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/TezosTypes.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/VotingOperations.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/util/CollectionOps.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseConversions.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosIndexer.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeFetchers.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeOperator.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperationsTest.scala
Labels: refactor/tech-debt

#845 843 - 844 - Missing proposals data from governance and fix incorrect rolls counts per level
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseConversions.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosGovernanceOperations.scala
Labels: bug

#837 add indices to speed up conseil
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/discovery/GenericPlatformDiscoveryOperationsTest.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/Tables.scala
  sql/conseil.sql
Labels: enhancement

#853 852 - verify correct parameters conversion in transactions
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/TezosOptics.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/TezosTypes.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/tezos/TezosOpticsTest.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/tezos/TezosTypesTest.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeOperator.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/bigmaps/BigMapsOperations.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperationsTestFixtures.scala
  project/Dependencies.scala
Labels: refactor/tech-debt, tests

#855 Track in comments the source of each implicit data fetcher
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeFetchers.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeOperator.scala
Labels: documentation, refactor/tech-debt
