Repository Cryptonomic/Conseil, pull requests merged in 2020-10, with the labels that each got.

#925 922 - missing rolls and bakers during test period
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/ConseilApi.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/ApiDataOperations.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/discovery/GenericPlatformDiscoveryOperations.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/discovery/GenericPlatformDiscoveryOperationsTest.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/generic/chain/DBIORunner.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/sql/DatabaseRunner.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/TezosTypes.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosIndexedDataOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosIndexer.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeOperator.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/processing/AccountsProcessor.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/processing/BakersProcessor.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/JsonDecodersTestFixtures.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperationsTest.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperationsTestFixtures.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosForkDatabaseOperationsTest.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosIndexedDataOperationsTest.scala
Labels: bug

#930 Minor fix to random test, testcontainer and postgres upgrade
  conseil-common-testkit/src/main/scala/tech/cryptonomic/conseil/common/testkit/InMemoryDatabase.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/TezosTypes.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseConversions.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeFetchers.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosNodeOperator.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/processing/BakingAndEndorsingRightsProcessor.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDataGenerationKit.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosInMemoryDatabaseSetup.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosIndexedDataOperationsTest.scala
  docker-compose.yml
  docker/docker-compose.yml
  project/Dependencies.scala
  project/plugins.sbt
Labels: refactor/tech-debt

#928 920 - compute and store the hash of smart contracts code when available
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/discovery/GenericPlatformDiscoveryOperationsTest.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/Tables.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseConversions.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/michelson/contracts/SmartContracts.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/michelson/contracts/TokenContracts.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/michelson/contracts/SmartContractsTest.scala
  sql/conseil.sql
Labels: data enhancement, dataschema-change-required

#931 922-2 mark bakers after delegates are fetched
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/tezos/TezosTypes.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/tezos/TezosTypesTest.scala
  conseil-lorre/src/main/resources/application.conf
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/config/LorreConfiguration.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosIndexer.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/processing/AccountsProcessor.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/processing/BakersProcessor.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/processing/BlocksProcessor.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperationsTest.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperationsTestFixtures.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosForkDatabaseOperationsTest.scala
  docker/docker-compose.yml
Labels: bug

#935 Only apply query predicates changes for fork-sensitive entities
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/ApiDataOperations.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataOperations.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataRoutes.scala
  conseil-api/src/main/scala/tech/cryptonomic/conseil/api/routes/platform/discovery/GenericPlatformDiscoveryOperations.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/bitcoin/BitcoinDataRoutesTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/ethereum/EthereumDataRoutesTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataOperationsTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataRoutesTest.scala
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosForkDataOperationsTest.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/generic/chain/DataOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/bigmaps/BigMapsConversions.scala
Labels: bug

#937 Change metadata config files to show block levels as Int
  conseil-api/src/main/resources/metadata/tezos.babylonnet.conf
  conseil-api/src/main/resources/metadata/tezos.carthagenet.conf
  conseil-api/src/main/resources/metadata/tezos.delphinet.conf
  conseil-api/src/main/resources/metadata/tezos.mainnet.conf
Labels: bug, configuration-change-required

#907 870 - Improve fees computation query performance
  conseil-api/src/test/scala/tech/cryptonomic/conseil/api/routes/platform/data/tezos/TezosDataOperationsTest.scala
  conseil-common-testkit/src/main/scala/tech/cryptonomic/conseil/common/testkit/util/RandomTestKit.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/sql/CustomProfileExtension.scala
  conseil-common/src/main/scala/tech/cryptonomic/conseil/common/util/MathUtil.scala
  conseil-common/src/test/scala/tech/cryptonomic/conseil/common/util/MathUtilTest.scala
  conseil-lorre/src/main/resources/application.conf
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/config/LorreConfiguration.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosFeeOperations.scala
  conseil-lorre/src/main/scala/tech/cryptonomic/conseil/indexer/tezos/TezosIndexer.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosDatabaseOperationsTest.scala
  conseil-lorre/src/test/scala/tech/cryptonomic/conseil/indexer/tezos/TezosForkDatabaseOperationsTest.scala
Labels: bug, configuration-change-required

#939 Added new baking/endorsing rights indexes
  sql/conseil.sql
Labels: enhancement
